# Start

In [1]:
import numpy as np

**1D array**

In [2]:
myarr1 = np.array([3,6,9,12], np.int64)  #1D array

In [3]:
myarr1

array([ 3,  6,  9, 12], dtype=int64)

In [4]:
myarr1[0]

3

**2D array**

In [5]:
myarr2 = np.array([[1,5,3,4]], np.int64) #2D array

In [6]:
myarr2

array([[1, 5, 3, 4]], dtype=int64)

In [7]:
myarr2[0][1]

5

**Info of an array**

In [8]:
myarr1.shape 

(4,)

In [9]:
myarr2.shape

(1, 4)

In [10]:
myarr1.dtype

dtype('int64')

In [11]:
myarr2.size

4

In [12]:
myarr2.ndim

2

In [13]:
myarr2.nbytes

32

**Modification of an array**

In [14]:
myarr1[0]=1

In [15]:
myarr1

array([ 1,  6,  9, 12], dtype=int64)

In [16]:
myarr2[0][3]=5

In [17]:
myarr2

array([[1, 5, 3, 5]], dtype=int64)

**Array creation from other python structures**

***From List***

In [18]:
listArray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [19]:
listArray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
listArray.dtype

dtype('int32')

In [21]:
listArray.shape

(3, 3)

In [22]:
listArray.size

9

***From Set***

In [23]:
setArray = np.array({1,2,2,3})

In [24]:
setArray

array({1, 2, 3}, dtype=object)

**Intrensic Numpy array creation objects**

***Zero Array***

In [25]:
zeros = np.zeros([3,3])

In [26]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [27]:
zeros.dtype

dtype('float64')

***Array using Range Function***

In [28]:
rngArray = np.arange(15) #create a numpy array

In [29]:
rngArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

***Array using Linspace Function***   *(Same Distance Between Elements)*

In [30]:
lnArray = np.linspace(1,10,5)   #(First element,Last Element,Element Number)

In [31]:
lnArray

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

***Empty Array***

In [32]:
emptyArray = np.empty([3,3]) # Empty array with random values

In [33]:
emptyArray

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

***Empty Like***

In [99]:
empty_like = np.empty_like(myarr1) #Empty any previous array

In [100]:
empty_like

array([       4294967296, 23925768157396992,              1084,
         140720308486912], dtype=int64)

***Identity Array***

In [36]:
ideArray = np.identity(5)

In [37]:
ideArray

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
ideArray.shape

(5, 5)

# Functions of array

***Reshape function***

In [39]:
arr = np.arange(30)

In [40]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [41]:
reshapeArr = arr.reshape(5,6) # it doesnt change the actual array

In [42]:
arr # main array doesnt reshape

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [43]:
reshapeArr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

***Ravel Function***  (it just simplify the reshaped array)

In [44]:
ravelArr= np.ravel(reshapeArr)

In [45]:
ravelArr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [46]:
reshapeArr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [47]:
ravelArr.shape

(30,)

***Index of Max number*** 

In [48]:
maxArr1 = np.array([1,2,3,4,5])

In [49]:
maxArr1.argmax() # Returns the index of max number

4

In [50]:
maxArr2 = np.array([[13,11,20],[15,5,3],[17,27,19]]) # 2d array

In [51]:
maxArr2.argmax()

7

***Index of Min Number***

In [52]:
minArr1 = np.array([6,7,8,9,10])

In [53]:
minArr1.argmin() # Returns the index of minimum number

0

In [54]:
minArr2 = np.array([[13,11,12],[16,14,15],[19,17,18]])

In [55]:
minArr2.argmin()

1

***Index of sorting array***

In [56]:
sortArr = np.array([3,21,4,6,1,66,7])

In [57]:
sortArr.argsort()

array([4, 0, 2, 3, 6, 1, 5], dtype=int64)

***Find element***

In [58]:
findArr = np.array([[11,5,6],[8,9,10]])

In [59]:
findArr

array([[11,  5,  6],
       [ 8,  9, 10]])

In [60]:
np.where(findArr>5)  # First array is for row, second array is for colomn

(array([0, 0, 1, 1, 1], dtype=int64), array([0, 2, 0, 1, 2], dtype=int64))

***Count non zero & Show***

In [101]:
countArr = np.array([[2,3,0],[1,0,5],[6,7,10]])

In [102]:
countArr

array([[ 2,  3,  0],
       [ 1,  0,  5],
       [ 6,  7, 10]])

In [103]:
np.count_nonzero(countArr)

7

In [64]:
np.nonzero(countArr) # First array for row, second array for colomn

(array([0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 0, 1, 2, 0, 1, 2], dtype=int64))

# Axis 

In [65]:
axisArr1 = np.array ([[1,2,3],[4,5,6],[7,8,9]])

In [66]:
axisArr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

***Axis = 0***

In [67]:
axisArr1.sum(axis=0) # axis=0 works on row
                     # so in this example 1+4+7 = 12, 2+5+8 = 15, 3+6+9 = 18

array([12, 15, 18])

***Axis = 1***

In [68]:
axisArr1.sum(axis=1) # axis=1 works on colomn
                     # so in this example 1+2+3 = 6, 4+5+6 = 15, 7+8+9 = 24

array([ 6, 15, 24])

***Transpose***

In [69]:
axisArr1.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

***Flat*** # To have a Iterator

In [70]:
axisArr1.flat

In [71]:
for i in axisArr1.flat:
    print(i)

1
2
3
4
5
6
7
8
9


***Max index using Axis***

In [72]:
maxArr2

array([[13, 11, 20],
       [15,  5,  3],
       [17, 27, 19]])

In [73]:
maxArr2.argmax(axis=0) # Represents 17,27,20 at colomn

array([2, 2, 0], dtype=int64)

In [74]:
maxArr2.argmax(axis=1) # Represents 13,15,27 at row

array([2, 0, 1], dtype=int64)

***Min index using Axis***

In [75]:
minArr2

array([[13, 11, 12],
       [16, 14, 15],
       [19, 17, 18]])

In [76]:
minArr2.argmin(axis=0) # Represents 13,11,12 at colomn

array([0, 0, 0], dtype=int64)

In [77]:
minArr2.argmin(axis=1) # Represents 11,14,17 at row

array([1, 1, 1], dtype=int64)

***Sorting using Axis***

In [78]:
sortAxisArray = np.array([[5,6,3],[25,51,66],[23,44,7]])

In [79]:
sortAxisArray

array([[ 5,  6,  3],
       [25, 51, 66],
       [23, 44,  7]])

In [80]:
sortAxisArray.argsort(axis=0)

array([[0, 0, 0],
       [2, 2, 2],
       [1, 1, 1]], dtype=int64)

In [81]:
sortAxisArray.argsort(axis=1)

array([[2, 0, 1],
       [0, 1, 2],
       [2, 0, 1]], dtype=int64)

# Math

In [82]:
A = np.array([[1,2,5],[3,5,7],[6,8,11]])

In [83]:
B = np.array([[3,4,7],[66,42,11],[6,8,10]])

In [84]:
sum = A+B

In [85]:
sum

array([[ 4,  6, 12],
       [69, 47, 18],
       [12, 16, 21]])

In [86]:
multiplication = A*B

In [87]:
multiplication

array([[  3,   8,  35],
       [198, 210,  77],
       [ 36,  64, 110]])

In [88]:
np.sqrt(A)

array([[1.        , 1.41421356, 2.23606798],
       [1.73205081, 2.23606798, 2.64575131],
       [2.44948974, 2.82842712, 3.31662479]])

In [89]:
A.sum()

48

In [90]:
A.max()

11

In [91]:
A.min()

1

# Space

In [92]:
import sys

In [93]:
py_arr = [1,2,3,4,5]

In [94]:
np_arr = np.array([4,5,6,7,8])

In [95]:
sys.getsizeof(1)*len(py_arr)

140

In [96]:
np_arr.itemsize*np_arr.size

20